FIX: Sanering av t4, q1 og flytting til default.
navikt/fp-abakus pull request #916
Opened 2020-09-04 10:28 UTC by mrsladek

2020-09-04 10:32 UTC, jolarsen reviewed
Hei, jeg ville kanskje ventet litt med denne .... Skapte trøbbel for alle apps
   - name: LOADBALANCER_URL
      value: https://fpabakus-q1.dev.adeo.no

2020-09-06 21:00 UTC, mrsladek commented
oppdatert

2020-09-06 21:39 UTC, jolarsen requested changes

2020-09-06 21:39 UTC, jolarsen commented on domenetjenester/vedtak/src/main/java/no/nav/foreldrepenger/abakus/vedtak/kafka/ApplicationIdUtil.java
> -        return System.getProperty("nais.app.name", "fpabakus") + "-" + System.getProperty("nais.namespace", "default");
Hei, jeg ville vært litt forsiktig med den. Husk at du committer med applicationId, så ved bytte av namespace bør man ta vare på de verdiene som brukes i dag.
Se eksempel: https://github.com/navikt/fpfordel/blob/master/domene/src/main/java/no/nav/foreldrepenger/mottak/hendelse/Journalf%C3%B8ringHendelseProperties.java

2020-09-07 08:27 UTC, mrsladek commented on domenetjenester/vedtak/src/main/java/no/nav/foreldrepenger/abakus/vedtak/kafka/ApplicationIdUtil.java
> -        return System.getProperty("nais.app.name", "fpabakus") + "-" + System.getProperty("nais.namespace", "default");
Enig... har fikset i koden.

2020-09-07 09:02 UTC, jolarsen approved these changes

2020-09-07 09:03 UTC, merged